kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: linda-nginx-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: linda-nginx-pv
  volumeMode: Filesystem
