---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-config-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.18.178.236
    path: /opt/nfs/nginx-data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          subPath: nginx-conf
          mountPath: /etc/nginx
      volumes:
      - name: nginx-conf
        persistentVolumeClaim:
          claimName: nginx-config-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    traefik.frontend.priority: '10'
    traefik.frontend.rule.type: PathPrefixStrip
spec:
 rules:
 - host: nickdevops.com
   http:
     paths:
     - path: /
       backend:
         serviceName: nginx-service
         servicePort: 80
