apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  nfs:
    path: /opt/nfs/jenkins-data
    server: 172.18.178.236 
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 10Gi
