apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dockerfile-claim
  namespace: devops
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi