apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linda-nginx-pvc
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi